### ISSUE TITLE
2.0.0 requires crypto, fails build

### ISSUE THREAD

**Issue by jim-lake** [mvayngrib/react-native-randombytes#2]
I get this problem in sjlc requiring crypto, not present and confusing react-native packager.  Using react-native 0.15.0.  Going back to 1.0.1 works fine.

```
react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/jlake/Library/Developer/Xcode/DerivedData/ButlerApp-gctemvenqiqwzvddskmlzxnnvprg/Build/Products/Debug-iphonesimulator/ButlerApp.app/main.jsbundle --assets-dest /Users/jlake/Library/Developer/Xcode/DerivedData/ButlerApp-gctemvenqiqwzvddskmlzxnnvprg/Build/Products/Debug-iphonesimulator/ButlerApp.app
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module crypto from /Users/jlake/sandbox/butler/butler-app/node_modules/react-native-randombytes/node_modules/sjcl/sjcl.js: Invalid directory /Users/node_modules/crypto
    at /Users/jlake/sandbox/butler/butler-app/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:323:15
    at tryCallOne (/Users/jlake/sandbox/butler/butler-app/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/jlake/sandbox/butler/butler-app/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/jlake/sandbox/butler/butler-app/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
See logs /var/folders/dk/9wx26dl95fgd2b3qs6q2_3q80000gn/T/react-packager.log
    at SocketClient._handleMessage (/Users/jlake/sandbox/butler/butler-app/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:131:23)
    at BunserBuf.<anonymous> (/Users/jlake/sandbox/butler/butler-app/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:52:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/jlake/sandbox/butler/butler-app/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/jlake/sandbox/butler/butler-app/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

**Comment by mvayngrib** [comment]
@jim-lake correct, 2.0.0 can't be used without some finagling. I currently use [rn-nodeify](https://github.com/mvayngrib/rn-nodeify) to handle such cases. See [example](https://github.com/mvayngrib/adexample)
